import { Inter } from "next/font/google"
import { Header } from "@/components"
import "./globals.css"
import "../styles/root-layout.scss"
import { AppContextProvider } from "@/components/AppContext"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContextProvider>
          <Header />
          {children}
        </AppContextProvider>
      </body>
    </html>
  )
}
